Change row filecount binding to a string property with empty string null coalescing, add detailed logging for dataerror events on datagridview
Attempting to fix/add diagnostics for error popup
    The following exception occurred in the DataGridView:
    System.lndexOutOfRangeException: Index 60 does not have a value.
        at System.Windows.Forms.DataGridView.DataGridViewDataConnection.GetError(Int32 rowIndex)